name: SonarQube Scan (Python)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Generate Full SonarQube Report
        run: |
            PROJECT_KEY="${{ secrets.SONAR_PROJECT_KEY }}"
            
            METRICS="bugs,vulnerabilities,code_smells,ncloc,reliability_rating,security_rating,sqale_rating"
            
            API_URL="${{ secrets.SONAR_HOST_URL }}/api/measures/component?component=${PROJECT_KEY}&metricKeys=${METRICS}"
        
            echo "Fetching results from: $API_URL"
        
            curl -u "${{ secrets.SONAR_TOKEN }}:" "$API_URL" -o sonar-report.json
        
            echo "----- SonarQube Report -----" > sonar-report.txt
            echo "Project: $PROJECT_KEY" >> sonar-report.txt
            echo "Generated on: $(date)" >> sonar-report.txt
            echo "" >> sonar-report.txt
        
            jq -r '.component.measures[] | "\(.metric): \(.value)"' sonar-report.json >> sonar-report.txt

      # Generate a reusable report
      #- name: Generate Scan Report
       # run: |
        #  echo "SonarQube Scan Report" > scan-report-${{ github.run_id }}.txt
         # echo "Repository: $GITHUB_REPOSITORY" >> scan-report-${{ github.run_id }}.txt
          #echo "Run ID: $GITHUB_RUN_ID" >> scan-report-${{ github.run_id }}.txt
          #echo "Timestamp: $(date)" >> scan-report-${{ github.run_id }}.txt
          #echo "Status: Scan Completed Successfully" >> scan-report-${{ github.run_id }}.txt

      # Upload the report to S3 bucket
      - name: Upload Report to S3
        run: |
          aws s3 cp scan-report-${{ github.run_id }}.txt s3://${{ secrets.S3_BUCKET_NAME }}/reports/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
