sonar.projectKey=SonarQubeScanning
sonar.projectName=SonarQubeScanning
sonar.projectVersion=1.0

# Where your source code is
sonar.sources=.

# Tell SonarQube it's Python
sonar.language=py
sonar.python.version=3
